[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
body = """
{% if version %}
## {{ version }} - {{ timestamp | date(format=\"%Y-%m-%d\") }}
{% else %}
## Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute=\"group\") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat=\"\\n\") | first | trim }}
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_preprocessors = []
commit_parsers = [
  { message = "(?i)fix", group = "Fixes" },
  { message = "(?i)add|implement|introduce", group = "Features" },
  { message = "(?i)move|refactor|cleanup|simplify|reunify|group|prepare", group = "Maintenance" },
  { message = ".*", group = "Other" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
toposort = false
sort_commits = "oldest"
