[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}## [Unreleased]
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{{ commit.message | upper_first }}\
{% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
tag_pattern = "v[0-9]*"
sort_commits = "oldest"

commit_parsers = [
  { message = "^feat", group = "added" },
  { message = "^fix", group = "fixed" },
  { message = "^perf", group = "performance" },
  { message = "^docs", group = "documentation" },
  { message = "^refactor", group = "changed" },
  { message = "^test", group = "testing" },
  { message = "^ci", group = "ci" },
  { message = "^build", group = "build" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "misc" },
]
